- name: Configure App
  hosts: app
  become: true

  roles:
    - role: app
    - role: jdauphant.nginx
      nginx_sites:
        default:
          - listen {{ listen }}
          - server_name "{{ server_name }}"
          - location / {
              proxy_pass {{ proxy_pass }};
            }
