- name: Configure application
  hosts: app
  become: true
  vars:
    db_host: 10.132.0.28
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma
    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/kalekseev/db_config
        owner: kalekseev
        group: kalekseev
    - name: enable puma
      systemd: name=puma enabled=yes
  handlers:
    - name: reload puma
      systemd: name=puma state=restarted
