- name: Deploy application
  hosts: app
  become: true
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/kalekseev/reddit
        version: monolith # <-- Указываем нужную ветку
      notify: reload puma
    - name: Bundle install
      bundler:
        state: present
        chdir: /home/kalekseev/reddit # <-- В какой директории выполнить команду bundle

  handlers:
    - name: reload puma
      systemd: name=puma state=restarted