- name: Apt update & Install Mongo
  hosts: default
  become: true
  tasks: 
    - name: Add an apt key by id from a keyserver
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: EA312927
    - name: Create a repolist file
      file:
        path: /etc/apt/sources.list.d/mongodb-org-3.2.list
        state: touch
        owner: root
        group: root
    - name: Insert repo in the repolist file
      blockinfile:
        path: /etc/apt/sources.list.d/mongodb-org-3.2.list
        block: |
          deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    - name: Fetch the latest version of mongo  
      apt:
        name: mongodb-org
        update_cache: yes
    - name: Replace a localhost entry with our own
      lineinfile:
        path: /etc/mongod.conf
        regexp: '127\.0\.0\.1'
        line: 0.0.0.0
    - name: enable service httpd and ensure it is not masked
      systemd:
        name: mongod
        enabled: yes
        masked: no
        
