---
- name: Configure MongoDB
  hosts: db
  tags: db-tag
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0
  tasks:
    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod

  handlers:
  - name: restart mongod
    service: name=mongod state=restarted


- name: Configure application
  hosts: app
  tags: app-tag
  become: true
  vars:
    db_host: 10.132.0.5
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma
    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/kalekseev/db_config
        owner: kalekseev
        group: kalekseev
    - name: enable puma
      systemd: name=puma enabled=yes
  handlers:
    - name: reload puma
      systemd: name=puma state=restarted

- name: Deploy application
  hosts: app
  tags: deploy-tag
  become: true
  tasks:  
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/kalekseev/reddit
        version: monolith # <-- Указываем нужную ветку
      tags: deploy-tag
      notify: reload puma
    - name: Bundle install
      bundler:
        state: present
        chdir: /home/kalekseev/reddit # <-- В какой директории выполнить команду bundle
      tags: deploy-tag

  handlers:
    - name: reload puma
      systemd: name=puma state=restarted      
